#!/usr/bin/env python3
"""
Comprehensive k-NN Species Analysis Summary V2
==============================================
Analyzes which species were used for predictions in k-NN and their accuracy rates.
Uses GTDB species names and parses neighbor data from .out files.

USAGE:
-----
1. Basic usage (uses config defaults):
   python knn_species_analysis.py

2. With custom paths via environment variables:
   export AMR_OUTPUT_DIR=/path/to/knn/results
   python knn_species_analysis.py

3. Specify custom metadata file:
   python knn_species_analysis.py --metadata /path/to/metadata.tsv

4. Specify custom input directory:
   python knn_species_analysis.py --input-dir /path/to/knn/results

REQUIREMENTS:
-----------
- .out files generated by knn_ultra_analysis_all_partitions.py
- Metadata file with GTDB species mapping

OUTPUT:
------
- Comprehensive species analysis report (.txt)
- CSV summary table (.csv)
- Analysis includes accuracy by species, neighbor usage patterns
"""

import pandas as pd
from pathlib import Path
import re
from collections import defaultdict
from datetime import datetime
import sys
import os
import argparse

# Add parent directories to path to import config
sys.path.append(str(Path(__file__).parent.parent.parent / 'utils'))
from config import get_config

def load_metadata(metadata_file=None):
    """Load GTDB species mapping from metadata"""
    if metadata_file is None:
        # Try to find metadata file in common locations
        config = get_config()
        possible_paths = [
            Path(config.data_dir) / "metadata_expanded_filt_copy.tsv",
            Path(config.labels_dir) / "metadata_expanded_filt_copy.tsv",
            Path(config.output_dir) / "metadata_expanded_filt_copy.tsv",
            Path(config.data_dir).parent / "metadata_expanded_filt_copy.tsv"
        ]
        
        metadata_file = None
        for path in possible_paths:
            if path.exists():
                metadata_file = str(path)
                break
        
        if metadata_file is None:
            raise FileNotFoundError("Metadata file not found. Please specify --metadata path or ensure metadata_expanded_filt_copy.tsv is in a standard location.")
    
    print(f"Loading metadata from: {metadata_file}")
    df = pd.read_csv(metadata_file, sep='\t')
    
    # Create mapping from genome_id prefix to GTDB species
    species_map = {}
    for _, row in df.iterrows():
        genome_id = str(row['genome_id'])
        # Extract the base genome ID (before the dot)
        base_id = genome_id.split('.')[0]
        gtdb_species = row['gtdb_species'] if pd.notna(row['gtdb_species']) else f"Unknown_{base_id}"
        species_map[base_id] = gtdb_species
        # Also store with full ID
        species_map[genome_id] = gtdb_species
    
    return species_map

def parse_out_file(out_file, species_map):
    """Parse .out file to extract neighbor species information"""
    with open(out_file, 'r') as f:
        content = f.read()
    
    # Extract individual sample analyses
    sample_pattern = r'\[\d+/\d+\] \w+: ([^\n]+)\nSpecies: ([^,]+), True AMR: ([RS])\n((?:.*\n)*?)(?=\[\d+/\d+\]|SUMMARY)'
    matches = re.findall(sample_pattern, content)
    
    species_stats = defaultdict(lambda: {
        'total': 0, 
        'correct': 0, 
        'R_total': 0, 
        'R_correct': 0,
        'S_total': 0,
        'S_correct': 0,
        'neighbors_used': defaultdict(int),
        'gtdb_name': ''
    })
    
    for match in matches:
        genome_id = match[0].strip()
        species_id = match[1].strip()
        true_amr = match[2].strip()
        neighbor_block = match[3]
        
        # Get GTDB species name
        base_species = species_id.split('.')[0] if '.' in species_id else species_id
        gtdb_name = species_map.get(base_species, species_map.get(species_id, f"Unknown_{species_id}"))
        
        # Parse neighbors
        neighbor_pattern = r'^\d+\s+([^\s]+)\s+([^\s]+)\s+([RS])\s+[\d.]+$'
        neighbor_lines = neighbor_block.strip().split('\n')
        
        # Determine prediction (majority vote of neighbors)
        neighbor_votes = {'R': 0, 'S': 0}
        
        for line in neighbor_lines:
            neighbor_match = re.match(neighbor_pattern, line.strip())
            if neighbor_match:
                neighbor_id = neighbor_match.group(1)
                neighbor_species = neighbor_match.group(2)
                neighbor_amr = neighbor_match.group(3)
                
                # Get GTDB name for neighbor
                base_neighbor = neighbor_species.split('.')[0] if '.' in neighbor_species else neighbor_species
                neighbor_gtdb = species_map.get(base_neighbor, species_map.get(neighbor_species, f"Unknown_{neighbor_species}"))
                
                species_stats[gtdb_name]['neighbors_used'][neighbor_gtdb] += 1
                neighbor_votes[neighbor_amr] += 1
        
        # Determine predicted AMR
        predicted_amr = 'R' if neighbor_votes['R'] > neighbor_votes['S'] else 'S'
        is_correct = (predicted_amr == true_amr)
        
        # Update statistics
        species_stats[gtdb_name]['total'] += 1
        species_stats[gtdb_name]['gtdb_name'] = gtdb_name
        
        if is_correct:
            species_stats[gtdb_name]['correct'] += 1
        
        if true_amr == 'R':
            species_stats[gtdb_name]['R_total'] += 1
            if is_correct:
                species_stats[gtdb_name]['R_correct'] += 1
        else:  # S
            species_stats[gtdb_name]['S_total'] += 1
            if is_correct:
                species_stats[gtdb_name]['S_correct'] += 1
    
    return species_stats

def main():
    parser = argparse.ArgumentParser(description='k-NN Species Analysis with GTDB Names')
    parser.add_argument('--input-dir', type=str,
                       help='Directory containing .out files from k-NN analysis (uses config default if not specified)')
    parser.add_argument('--metadata', type=str,
                       help='Path to metadata TSV file with GTDB species mapping')
    parser.add_argument('--output-dir', type=str,
                       help='Directory for output files (uses config default if not specified)')
    
    args = parser.parse_args()
    
    # Load configuration
    config = get_config()
    
    # Use config defaults if arguments not provided
    input_dir = args.input_dir if args.input_dir else config.get_output_path('knn_analysis')
    output_dir_path = args.output_dir if args.output_dir else config.get_output_path('knn_species_analysis')
    
    input_path = Path(input_dir)
    output_dir = Path(output_dir_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Input directory: {input_path}")
    print(f"Output directory: {output_dir}")
    
    # Load species mapping
    print("Loading GTDB species mapping...")
    species_map = load_metadata(args.metadata)
    
    # Define partitions and feature types
    partitions = ['val_outside', 'test_outside', 'val_overlapped', 'test_overlapped']
    feature_types = ['minirocket', 'baseline']
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = output_dir / f"species_comprehensive_summary_gtdb_{timestamp}.txt"
    
    with open(output_file, 'w') as f:
        f.write("=" * 100 + "\n")
        f.write("COMPREHENSIVE k-NN SPECIES ANALYSIS SUMMARY WITH GTDB NAMES\n")
        f.write("=" * 100 + "\n\n")
        
        for feature_type in feature_types:
            f.write("\n" + "🔬" * 50 + "\n")
            f.write(f"{feature_type.upper()} FEATURES\n")
            f.write("🔬" * 50 + "\n\n")
            
            for partition in partitions:
                # Find latest .out file
                out_pattern = f"knn_{feature_type}_{partition}_*.out"
                out_files = list(input_path.glob(out_pattern))
                
                if not out_files:
                    f.write(f"\n⚠️  No data for {partition}\n")
                    continue
                
                # Use the latest file
                out_file = sorted(out_files)[-1]
                f.write(f"\n{'='*80}\n")
                f.write(f"{partition.upper()} - {feature_type.upper()}\n")
                f.write(f"{'='*80}\n")
                f.write(f"Source: {out_file.name}\n\n")
                
                species_stats = parse_out_file(out_file, species_map)
                
                # Sort by total samples
                sorted_species = sorted(species_stats.items(), 
                                       key=lambda x: x[1]['total'], 
                                       reverse=True)
                
                f.write(f"Total GTDB species analyzed: {len(sorted_species)}\n")
                f.write(f"{'='*80}\n\n")
                
                for gtdb_name, stats in sorted_species:
                    accuracy = stats['correct'] / stats['total'] * 100 if stats['total'] > 0 else 0
                    f.write(f"SPECIES: {gtdb_name}\n")
                    f.write(f"  Overall: {stats['correct']}/{stats['total']} ({accuracy:.1f}%)\n")
                    
                    if stats['R_total'] > 0:
                        r_acc = stats['R_correct'] / stats['R_total'] * 100
                        f.write(f"  Resistant (R): {stats['R_correct']}/{stats['R_total']} ({r_acc:.1f}%)\n")
                    else:
                        f.write(f"  Resistant (R): 0/0 (N/A)\n")
                    
                    if stats['S_total'] > 0:
                        s_acc = stats['S_correct'] / stats['S_total'] * 100
                        f.write(f"  Susceptible (S): {stats['S_correct']}/{stats['S_total']} ({s_acc:.1f}%)\n")
                    else:
                        f.write(f"  Susceptible (S): 0/0 (N/A)\n")
                    
                    # Top 10 species used as neighbors
                    if stats['neighbors_used']:
                        f.write(f"  Top GTDB species used for prediction:\n")
                        top_neighbors = sorted(stats['neighbors_used'].items(), 
                                             key=lambda x: x[1], 
                                             reverse=True)[:10]
                        
                        total_neighbor_count = sum(stats['neighbors_used'].values())
                        for neighbor, count in top_neighbors:
                            pct = count / total_neighbor_count * 100 if total_neighbor_count > 0 else 0
                            f.write(f"    - {neighbor}: {count} times ({pct:.1f}%)\n")
                    
                    f.write("\n")
                
                # Summary statistics
                f.write(f"\n{'-'*40}\n")
                f.write(f"PARTITION SUMMARY - {partition.upper()}\n")
                f.write(f"{'-'*40}\n")
                
                total_samples = sum(s['total'] for s in species_stats.values())
                total_correct = sum(s['correct'] for s in species_stats.values())
                total_r = sum(s['R_total'] for s in species_stats.values())
                total_r_correct = sum(s['R_correct'] for s in species_stats.values())
                total_s = sum(s['S_total'] for s in species_stats.values())
                total_s_correct = sum(s['S_correct'] for s in species_stats.values())
                
                f.write(f"Total samples: {total_samples}\n")
                if total_samples > 0:
                    f.write(f"Overall accuracy: {total_correct}/{total_samples} ({total_correct/total_samples*100:.1f}%)\n")
                if total_r > 0:
                    f.write(f"R accuracy: {total_r_correct}/{total_r} ({total_r_correct/total_r*100:.1f}%)\n")
                if total_s > 0:
                    f.write(f"S accuracy: {total_s_correct}/{total_s} ({total_s_correct/total_s*100:.1f}%)\n")
                
                # Top species across all predictions
                all_neighbors = defaultdict(int)
                for stats in species_stats.values():
                    for neighbor, count in stats['neighbors_used'].items():
                        all_neighbors[neighbor] += count
                
                f.write(f"\nTop 15 GTDB species used across all predictions in {partition}:\n")
                top_overall = sorted(all_neighbors.items(), key=lambda x: x[1], reverse=True)[:15]
                total_uses = sum(all_neighbors.values())
                for species, count in top_overall:
                    pct = count / total_uses * 100 if total_uses > 0 else 0
                    f.write(f"  {species}: {count} times ({pct:.1f}%)\n")
                
                f.write("\n")
    
    print(f"✅ Comprehensive GTDB species summary saved to: {output_file}")
    
    # Also create a CSV summary
    csv_output = output_dir / f"species_summary_gtdb_table_{timestamp}.csv"
    rows = []
    
    for feature_type in feature_types:
        for partition in partitions:
            out_pattern = f"knn_{feature_type}_{partition}_*.out"
            out_files = list(input_path.glob(out_pattern))
            if not out_files:
                continue
            
            out_file = sorted(out_files)[-1]
            species_stats = parse_out_file(out_file, species_map)
            
            for gtdb_name, stats in species_stats.items():
                rows.append({
                    'feature_type': feature_type,
                    'partition': partition,
                    'gtdb_species': gtdb_name,
                    'total': stats['total'],
                    'correct': stats['correct'],
                    'accuracy_pct': stats['correct'] / stats['total'] * 100 if stats['total'] > 0 else 0,
                    'R_total': stats['R_total'],
                    'R_correct': stats['R_correct'],
                    'R_accuracy_pct': stats['R_correct'] / stats['R_total'] * 100 if stats['R_total'] > 0 else 0,
                    'S_total': stats['S_total'],
                    'S_correct': stats['S_correct'],
                    'S_accuracy_pct': stats['S_correct'] / stats['S_total'] * 100 if stats['S_total'] > 0 else 0,
                    'top_neighbor_species': list(sorted(stats['neighbors_used'].items(), key=lambda x: x[1], reverse=True)[:1])[0][0] if stats['neighbors_used'] else 'None'
                })
    
    df_summary = pd.DataFrame(rows)
    df_summary.to_csv(csv_output, index=False)
    print(f"✅ CSV summary saved to: {csv_output}")

if __name__ == "__main__":
    main()